spring:
  cloud:
    gateway:
      routes:
        - id: book-server
          uri: http://localhost:8081
          predicates:
            - Path=/books
        - id: book-sotre-server
          uri: http://localhost:8082
          predicates:
            - Path=/book-stores
